apiVersion: v1
kind: Service
metadata:
  name: django-mysql
  labels:
    app: django
spec:
  ports:
    - port: 3306
  selector:
    app: django
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim1
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: django-mysql
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass1
              key: password
        - name: MYSQL_DATABASE
          value: db
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim1
