# Generated by Django 2.2.4 on 2020-06-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(default=None, max_length=100, null=True)),
                ('expiry_month', models.CharField(default=None, max_length=2, null=True)),
                ('expiry_year', models.CharField(default=None, max_length=2, null=True)),
                ('cvv', models.CharField(default=None, max_length=5, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'customer card details',
                'db_table': 'customercarddetails',
            },
        ),
    ]
